[features]
seeds = false
skip-lint = false

[programs.localnet]
neet_clearing_house = "2bvorArGtZTma2WoLtxejbtokywxyAd3FEVboT7Vzuww"
neet_amm            = "CfqUg2Mv7PcPEh5rLuUvAfGugYva7GZStDmFYkspgNYo"
neet_oracle_adapter = "9ejr5z91rYKboS8bG8iDE9t3iSf2jVCrVbBy2pRHWexS"
neet_funding        = "91G4AGvfd6JfJqWojEVrapA4615sNrrr2Tddm9zmnDRL"
neet_liquidation    = "8t58GABFWM4eXqHhYcnxgSLE3e2W7Wvmz5QRqjbms6NP"
neet_insurance      = "Hmt6dN8xz3ej3841376toAEbe1B6PxsMuZJXqVBdGTEM"
neet_treasury       = "4q5nwJxtYikZoHNxxh1t7mobi6nGwVsVeC6nu6uxpj1S"

[programs.devnet]
neet_clearing_house = "2bvorArGtZTma2WoLtxejbtokywxyAd3FEVboT7Vzuww"
neet_amm            = "CfqUg2Mv7PcPEh5rLuUvAfGugYva7GZStDmFYkspgNYo"
neet_oracle_adapter = "9ejr5z91rYKboS8bG8iDE9t3iSf2jVCrVbBy2pRHWexS"
neet_funding        = "91G4AGvfd6JfJqWojEVrapA4615sNrrr2Tddm9zmnDRL"
neet_liquidation    = "8t58GABFWM4eXqHhYcnxgSLE3e2W7Wvmz5QRqjbms6NP"
neet_insurance      = "Hmt6dN8xz3ej3841376toAEbe1B6PxsMuZJXqVBdGTEM"
neet_treasury       = "4q5nwJxtYikZoHNxxh1t7mobi6nGwVsVeC6nu6uxpj1S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
  "programs/neet_clearing_house",
  "programs/neet_amm",
  "programs/neet_oracle_adapter",
  "programs/neet_funding",
  "programs/neet_liquidation",
  "programs/neet_insurance",
  "programs/neet_treasury",
]
